/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef QX-T34_PRIVATE_H
#define QX-T34_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.1.924"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	924
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.1.924"
#define FILE_DESCRIPTION	"还没想好……"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.1.924"

#endif /*QX-T34_PRIVATE_H*/
